patterns = [
    (r'^[A-Z].*', 'n.prop'),
    (r'^\d+$', 'num'),
    (r'^\d+\D+$', 'num'),
    (r'^\D+w', 'n'),
    (r'^\D+na$', 'n'), 
    (r'^\D+(l|n)ata\D+$','n'),
    ('^\D+(l|n)ama$', 'adj'),
    (r'^\D+la$', 'n'), 
    (r'^\D+ra$', 'v'),
    (r'^\D+ya$', 'n'),
    (r'^\D+bali$','ptcp'),
    (r'^\D+ka$', 'n'),
    (r'^\D+ta$', 'ptcp'),
    (r'^\D+ntan$', 'adj'),
    (r'^\D+baa$', 'n'),
    (r'^\D+baga$', 'n'),
    (r'^\D+li$','n'),
    (r'^\D+(len|nen)$', 'ptcp'),
    (r'^\D+(lan|ran|ni|ɲɔgɔn|ɲwaa?n)$', 'n'),
    (r'^\D*ɲwan', 'n'),
    (r'^(lá|ná)\D+$', 'v'),
    (r'^\D+(man|nan)$', 'adj'),
    (r'^\D+(lan|ran)$', 'n'),
    (r'^\D+(la|na|lan|nan|ma|man)\D+$','adj'),
    (r'^\D+(l|n)en$', 'ptcp'),
    (r'\D+(rɔ|nɔ)\D+$', 'adj'),
    (r'^(lá|ná|mà|màn|rá|rɔ́|sɔ̀)\D+$' ,'v')
]
